[technote]
id = "SITCOMTN-142"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-142.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-142"
github_default_branch = "main"
date_created = 2024-10-04T13:37:13Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Bekah"
name.family = "Polen"
internal_id = "polenb"

[[technote.authors.affiliations]]
name = "Department of Physics"
internal_id = "Duke"
address = "Duke University, Durham, NC 27708, USA"
